services:
  php:
    build:
      context: .
      args:
        PHP_VERSION: 8.2
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
    ports:
      - "8060:8080"
    restart: always
    working_dir: /var/www/html
    command: bash -c "composer install && php -S 0.0.0.0:8080"
    depends_on:
      pgvector: { condition: service_healthy }

  pgvector:
    image: ankane/pgvector
    restart: always
    environment:
      POSTGRES_USER: docGPT
      POSTGRES_PASSWORD: doc_gpt_password
      POSTGRES_DB: docGPT
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ${PWD}/data/pgvector/pg_vector_init.sql:/docker-entrypoint-initdb.d/1.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U docGPT -d docGPT -t 3" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    profiles:
      - debug
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.ca
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80"
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ${PWD}/data/pgadmin/servers.json:/pgadmin4/servers.json

volumes:
  pg_data:
  pgadmin:
