on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit-test:
    name: "Build and test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start the containers
        run: docker compose up -d

      ## TODO: fix the linting and add it back
      #      - name: Run the lint
      #        run: ./dev lint

      - name: Run the tests
        run: ./dev test

      - name: Stop the containers
        if: always()
        run: docker compose down -v
